import type { StudyDesignKind } from "./studyDesign";
import { contribution, type StudyBuildRegistryContribution } from "./studyBuildRegistry";

type ConcreteDesignKind = Exclude<StudyDesignKind, "">;

export type StudyDesignModuleRegistry = Readonly<Record<ConcreteDesignKind, StudyBuildRegistryContribution>>;

export const STUDY_DESIGN_MODULE_REGISTRY: StudyDesignModuleRegistry = {
  "randomized-between": contribution({
    modules: [
      {
        id: "design.randomized.allocation",
        moduleKind: "assignment",
        status: "required",
        sourceKinds: ["design", "assignment"],
        proposedBlockRoles: ["allocation", "assignment-receipt"],
        proposedVariableRoles: ["condition-id", "assignment-receipt"],
        rationale: "A randomized between-groups design requires an auditable allocation before condition-specific procedures.",
      },
      {
        id: "design.randomized.condition-routing",
        moduleKind: "condition-routing",
        status: "required",
        sourceKinds: ["design", "assignment"],
        proposedBlockRoles: ["condition-branch", "condition-procedure"],
        proposedVariableRoles: ["condition-id"],
        rationale: "Participants must receive the procedure associated with their assigned condition.",
      },
      {
        id: "design.randomized.outcomes",
        moduleKind: "outcome-collection",
        status: "required",
        sourceKinds: ["design", "measures"],
        proposedBlockRoles: ["primary-outcome", "secondary-outcome"],
        proposedVariableRoles: ["primary-outcome", "secondary-outcome"],
        rationale: "Comparable outcomes must be produced after allocation for every planned condition.",
      },
      {
        id: "design.randomized.manipulation-check",
        moduleKind: "manipulation-check",
        status: "recommended",
        sourceKinds: ["design", "measures"],
        proposedBlockRoles: ["manipulation-check"],
        proposedVariableRoles: ["manipulation-check"],
        rationale: "A manipulation check can document whether the intended condition difference was experienced.",
      },
    ],
    checks: [
      {
        id: "check.randomized.conditions",
        level: "required",
        repairTarget: "participants",
        message: "Define at least two named conditions and the planned allocation ratio.",
        sourceKinds: ["design", "assignment"],
      },
      {
        id: "check.randomized.post-assignment-outcome",
        level: "required",
        repairTarget: "measures",
        message: "Map at least one comparable outcome produced after assignment in every condition.",
        sourceKinds: ["design", "measures"],
      },
      {
        id: "check.randomized.contamination",
        level: "recommended",
        repairTarget: "design",
        message: "Review allocation concealment, contamination, balance, and manipulation risks.",
        sourceKinds: ["design"],
      },
    ],
    capabilityRequests: [
      {
        id: "simple-random-assignment",
        requiredForRunnable: true,
        repairTarget: "studio",
        rationale: "The selected design requires runtime allocation across named conditions.",
        sourceKinds: ["design", "assignment", "runtime"],
      },
      {
        id: "condition-specific-flow",
        requiredForRunnable: true,
        repairTarget: "studio",
        rationale: "Assigned conditions require deterministic condition-aware routing.",
        sourceKinds: ["design", "assignment", "runtime"],
      },
    ],
  }),
  "within-subjects": contribution({
    modules: [
      {
        id: "design.within.repeated-condition-loop",
        moduleKind: "repeated-condition-loop",
        status: "required",
        sourceKinds: ["design", "assignment"],
        proposedBlockRoles: ["condition-loop", "between-condition-break"],
        proposedVariableRoles: ["condition-id", "condition-order", "repetition-index"],
        rationale: "A within-subjects design requires each participant to complete repeated conditions or measurements.",
      },
      {
        id: "design.within.counterbalancing",
        moduleKind: "counterbalancing",
        status: "required",
        sourceKinds: ["design", "assignment"],
        proposedBlockRoles: ["order-assignment"],
        proposedVariableRoles: ["order-id"],
        rationale: "Condition order must be explicit so order effects can be prevented, estimated, or justified.",
      },
      {
        id: "design.within.repeated-outcomes",
        moduleKind: "outcome-collection",
        status: "required",
        sourceKinds: ["design", "measures"],
        proposedBlockRoles: ["repeated-outcome"],
        proposedVariableRoles: ["participant-id", "condition-id", "repeated-outcome"],
        rationale: "Repeated outcomes need stable participant and condition identity for within-participant analysis.",
      },
      {
        id: "design.within.carryover-plan",
        moduleKind: "carryover-management",
        status: "recommended",
        sourceKinds: ["design"],
        proposedBlockRoles: ["washout-or-break"],
        proposedVariableRoles: ["fatigue-check", "carryover-check"],
        rationale: "Fatigue, practice, and carryover can bias later conditions and require an explicit plan.",
      },
    ],
    checks: [
      {
        id: "check.within.order",
        level: "required",
        repairTarget: "participants",
        message: "Define the condition order or counterbalancing strategy.",
        sourceKinds: ["design", "assignment"],
      },
      {
        id: "check.within.repeated-outcome",
        level: "required",
        repairTarget: "measures",
        message: "Verify that comparable outcomes are produced for every repeated condition.",
        sourceKinds: ["design", "measures"],
      },
      {
        id: "check.within.carryover",
        level: "recommended",
        repairTarget: "design",
        message: "Review fatigue, practice, carryover, break, and washout requirements.",
        sourceKinds: ["design"],
      },
    ],
    capabilityRequests: [
      {
        id: "repeated-trial-loops",
        requiredForRunnable: true,
        repairTarget: "studio",
        rationale: "The selected design requires repeatable condition or trial execution.",
        sourceKinds: ["design", "runtime"],
      },
      {
        id: "counterbalanced-condition-orders",
        requiredForRunnable: false,
        repairTarget: "studio",
        rationale: "Counterbalancing may be required depending on the approved order-effects plan.",
        sourceKinds: ["design", "assignment", "runtime"],
      },
    ],
  }),
  "quasi-experimental": contribution({
    modules: [
      {
        id: "design.quasi.group-source",
        moduleKind: "existing-group-mapping",
        status: "required",
        sourceKinds: ["design", "assignment"],
        proposedBlockRoles: ["group-or-exposure-capture"],
        proposedVariableRoles: ["group-id", "exposure-status"],
        rationale: "Quasi-experimental groups arise from an existing group, exposure, or intervention rather than Cerise randomization.",
      },
      {
        id: "design.quasi.baseline-covariates",
        moduleKind: "baseline-covariates",
        status: "required",
        sourceKinds: ["design", "measures"],
        proposedBlockRoles: ["baseline-measure", "covariate-measure"],
        proposedVariableRoles: ["baseline-outcome", "covariate"],
        rationale: "Baseline and covariate evidence is needed to assess group comparability and confounding.",
      },
      {
        id: "design.quasi.exposure-timing",
        moduleKind: "exposure-timing",
        status: "recommended",
        sourceKinds: ["design"],
        proposedBlockRoles: ["exposure-timing"],
        proposedVariableRoles: ["exposure-time"],
        rationale: "The timing of naturally occurring exposure or intervention should be represented explicitly.",
      },
    ],
    checks: [
      {
        id: "check.quasi.no-randomization-claim",
        level: "required",
        repairTarget: "design",
        message: "Confirm that participant-facing and analytic materials do not claim random assignment.",
        sourceKinds: ["design", "assignment"],
      },
      {
        id: "check.quasi.comparability",
        level: "required",
        repairTarget: "measures",
        message: "Define the baseline or covariate evidence used to assess comparability and confounding.",
        sourceKinds: ["design", "measures"],
      },
    ],
    capabilityRequests: [{
      id: "naturally-occurring-group-mapping",
      requiredForRunnable: true,
      repairTarget: "studio",
      rationale: "The runtime must record existing group or exposure identity without assigning it randomly.",
      sourceKinds: ["design", "assignment", "runtime"],
    }],
  }),
  "cross-sectional-survey": contribution({
    modules: [
      {
        id: "design.survey.measure-sections",
        moduleKind: "survey-sections",
        status: "required",
        sourceKinds: ["design", "measures"],
        proposedBlockRoles: ["survey-instructions", "measure-section"],
        proposedVariableRoles: ["survey-response"],
        rationale: "A cross-sectional survey needs structured measure sections tied to the evidence plan.",
      },
      {
        id: "design.survey.skip-logic",
        moduleKind: "skip-logic",
        status: "recommended",
        sourceKinds: ["design", "measures"],
        proposedBlockRoles: ["conditional-question"],
        proposedVariableRoles: ["routing-response"],
        rationale: "Explicit skip logic reduces irrelevant questions without silently changing the target sample.",
      },
      {
        id: "design.survey.demographics",
        moduleKind: "demographics",
        status: "optional",
        sourceKinds: ["design", "participants"],
        proposedBlockRoles: ["optional-demographics"],
        proposedVariableRoles: ["demographic"],
        rationale: "Collect demographic variables only when the research question, sampling plan, or fairness review requires them.",
      },
    ],
    checks: [
      {
        id: "check.survey.measure-coverage",
        level: "required",
        repairTarget: "measures",
        message: "Map every research question to at least one survey measure or evidence source.",
        sourceKinds: ["design", "measures"],
      },
      {
        id: "check.survey.burden",
        level: "recommended",
        repairTarget: "studio",
        message: "Rehearse completion time, mobile reflow, missingness, optional items, and sensitive-question burden.",
        sourceKinds: ["design", "setting", "participants"],
      },
    ],
    capabilityRequests: [{
      id: "responsive-forms-and-branching",
      requiredForRunnable: true,
      repairTarget: "studio",
      rationale: "The survey requires responsive input controls and deterministic skip logic.",
      sourceKinds: ["design", "runtime"],
    }],
  }),
  longitudinal: contribution({
    modules: [
      {
        id: "design.longitudinal.wave-plan",
        moduleKind: "wave-plan",
        status: "required",
        sourceKinds: ["design"],
        proposedBlockRoles: ["wave-definition", "wave-schedule"],
        proposedVariableRoles: ["wave-id", "scheduled-interval"],
        rationale: "A longitudinal study must define multiple waves and their intended intervals.",
      },
      {
        id: "design.longitudinal.measure-identity",
        moduleKind: "repeated-measure-identity",
        status: "required",
        sourceKinds: ["design", "measures"],
        proposedBlockRoles: ["repeated-measure"],
        proposedVariableRoles: ["participant-link-id", "wave-id", "repeated-outcome"],
        rationale: "Comparable measures need stable identity across waves to detect change without silent version drift.",
      },
      {
        id: "design.longitudinal.recontact",
        moduleKind: "recontact-and-retention",
        status: "required",
        sourceKinds: ["design", "participants"],
        proposedBlockRoles: ["recontact-plan", "withdrawal-plan"],
        proposedVariableRoles: ["recontact-status", "withdrawal-status"],
        rationale: "Multiple waves require an explicit recontact, retention, attrition, and withdrawal process.",
      },
    ],
    checks: [
      {
        id: "check.longitudinal.waves",
        level: "required",
        repairTarget: "design",
        message: "Define wave count, intervals, reminders, versioning, partial-wave handling, and reconsent triggers.",
        sourceKinds: ["design"],
      },
      {
        id: "check.longitudinal.identity",
        level: "required",
        repairTarget: "participants",
        message: "Provide the institutionally appropriate participant-linkage and recontact workflow before calling the study runnable.",
        sourceKinds: ["design", "participants"],
      },
    ],
    capabilityRequests: [
      {
        id: "cross-session-participant-identity",
        requiredForRunnable: true,
        repairTarget: "participants",
        rationale: "Repeated waves must link the correct participant across sessions without making unsupported privacy claims.",
        sourceKinds: ["design", "participants", "runtime"],
      },
      {
        id: "scheduling-reminders-and-recontact",
        requiredForRunnable: true,
        repairTarget: "participants",
        rationale: "A runnable multi-wave workflow needs scheduling, reminders, and controlled recontact.",
        sourceKinds: ["design", "participants", "runtime"],
      },
    ],
  }),
  observational: contribution({
    modules: [
      {
        id: "design.observational.coding-schema",
        moduleKind: "observation-schema",
        status: "required",
        sourceKinds: ["design", "measures"],
        proposedBlockRoles: ["observer-instructions", "event-or-interval-coding"],
        proposedVariableRoles: ["event-code", "interval-id", "timestamp"],
        rationale: "Structured observation requires an explicit behavior, event, or interval coding schema.",
      },
      {
        id: "design.observational.context",
        moduleKind: "observation-context",
        status: "required",
        sourceKinds: ["design", "setting"],
        proposedBlockRoles: ["context-capture"],
        proposedVariableRoles: ["observation-context"],
        rationale: "The natural context of an observation is part of the evidence and must be captured consistently.",
      },
      {
        id: "design.observational.reliability",
        moduleKind: "observer-reliability",
        status: "recommended",
        sourceKinds: ["design", "measures"],
        proposedBlockRoles: ["observer-training"],
        proposedVariableRoles: ["observer-id"],
        rationale: "Observer training and reliability evidence reduce coding drift and subjective inconsistency.",
      },
    ],
    checks: [
      {
        id: "check.observational.privacy",
        level: "required",
        repairTarget: "participants",
        message: "Resolve privacy expectations, third-party data, notice or consent status, and recording before collection.",
        sourceKinds: ["design", "participants", "setting"],
      },
      {
        id: "check.observational.reliability",
        level: "recommended",
        repairTarget: "measures",
        message: "Define observer training, drift review, and inter-rater reliability when multiple observers are used.",
        sourceKinds: ["design", "measures"],
      },
    ],
    capabilityRequests: [{
      id: "structured-observer-workflow",
      requiredForRunnable: true,
      repairTarget: "studio",
      rationale: "The selected design requires structured observer-entered evidence and context capture.",
      sourceKinds: ["design", "runtime"],
    }],
  }),
  qualitative: contribution({
    modules: [
      {
        id: "design.qualitative.topic-guide",
        moduleKind: "qualitative-topic-guide",
        status: "required",
        sourceKinds: ["design", "measures"],
        proposedBlockRoles: ["topic-guide", "open-prompt", "probe"],
        proposedVariableRoles: ["qualitative-source"],
        rationale: "Qualitative inquiry uses topics, prompts, and probes rather than forced predictor and outcome fields.",
      },
      {
        id: "design.qualitative.participant-control",
        moduleKind: "participant-controlled-response",
        status: "required",
        sourceKinds: ["design", "participants"],
        proposedBlockRoles: ["pause-skip-stop-controls"],
        proposedVariableRoles: ["response-status"],
        rationale: "Participants need meaningful control to pause, skip, or stop open-ended and potentially sensitive discussion.",
      },
      {
        id: "design.qualitative.recording-choice",
        moduleKind: "separate-recording-choice",
        status: "recommended",
        sourceKinds: ["design", "participants"],
        proposedBlockRoles: ["recording-choice", "recording-alternative"],
        proposedVariableRoles: ["recording-choice"],
        rationale: "Audio or video capture needs a separate declared choice and a bounded alternative when recording is optional.",
      },
      {
        id: "design.qualitative.data-plan",
        moduleKind: "qualitative-data-plan",
        status: "required",
        sourceKinds: ["design", "measures"],
        proposedBlockRoles: ["transcription-and-deidentification-plan"],
        proposedVariableRoles: ["transcript-id", "quote-permission"],
        rationale: "Transcription, de-identification, quotation, retention, and access decisions are part of the evidence contract.",
      },
    ],
    checks: [
      {
        id: "check.qualitative.no-forced-quant-fields",
        level: "required",
        repairTarget: "measures",
        message: "Use qualitative concepts, evidence sources, and interpretation mappings without requiring statistical outcome roles.",
        sourceKinds: ["design", "measures"],
      },
      {
        id: "check.qualitative.recording",
        level: "required",
        repairTarget: "participants",
        message: "Declare recording, transcription, quotation, retention, access, and deletion behavior before adding capture modules.",
        sourceKinds: ["design", "participants"],
      },
    ],
    capabilityRequests: [{
      id: "individual-qualitative-session",
      requiredForRunnable: true,
      repairTarget: "studio",
      rationale: "The current profile needs participant-controlled open response and optional bounded local recording.",
      sourceKinds: ["design", "runtime"],
    }],
  }),
  "mixed-methods": contribution({
    modules: [
      {
        id: "design.mixed.quantitative-lane",
        moduleKind: "quantitative-lane",
        status: "required",
        sourceKinds: ["design", "measures"],
        proposedBlockRoles: ["quantitative-procedure"],
        proposedVariableRoles: ["quantitative-measure"],
        rationale: "Mixed methods requires an explicitly named quantitative lane with its own evidence mapping.",
      },
      {
        id: "design.mixed.qualitative-lane",
        moduleKind: "qualitative-lane",
        status: "required",
        sourceKinds: ["design", "measures"],
        proposedBlockRoles: ["qualitative-procedure"],
        proposedVariableRoles: ["qualitative-source"],
        rationale: "Mixed methods requires an explicitly named qualitative lane that is not collapsed into numeric variable roles.",
      },
      {
        id: "design.mixed.integration",
        moduleKind: "mixed-methods-integration",
        status: "required",
        sourceKinds: ["design", "measures"],
        proposedBlockRoles: ["lane-sequence", "integration-metadata"],
        proposedVariableRoles: ["lane-id", "cross-lane-link-id"],
        rationale: "The sequence, priority, sample linkage, integration question, and merge point must be explicit.",
      },
    ],
    checks: [
      {
        id: "check.mixed.separate-lanes",
        level: "required",
        repairTarget: "measures",
        message: "Validate quantitative and qualitative lanes independently before reviewing their integration.",
        sourceKinds: ["design", "measures"],
      },
      {
        id: "check.mixed.integration",
        level: "required",
        repairTarget: "design",
        message: "Define sequence, priority, sample linkage, integration question, and planned merge point.",
        sourceKinds: ["design", "measures", "participants"],
      },
    ],
    capabilityRequests: [
      {
        id: "responsive-forms-and-branching",
        requiredForRunnable: true,
        repairTarget: "studio",
        rationale: "The quantitative lane requires supported response controls and routing.",
        sourceKinds: ["design", "runtime"],
      },
      {
        id: "individual-qualitative-session",
        requiredForRunnable: true,
        repairTarget: "studio",
        rationale: "The qualitative lane requires participant-controlled open response.",
        sourceKinds: ["design", "runtime"],
      },
      {
        id: "mixed-methods-integration-metadata",
        requiredForRunnable: false,
        repairTarget: "measures",
        rationale: "The integration plan must be preserved even though integration occurs during analysis rather than participant runtime.",
        sourceKinds: ["design", "measures", "runtime"],
      },
    ],
  }),
};

export function getStudyDesignContribution(
  designKind: ConcreteDesignKind,
): StudyBuildRegistryContribution {
  return STUDY_DESIGN_MODULE_REGISTRY[designKind];
}
